{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "#!pip install \"ray[tune]\" optuna"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.optim as optim\n",
    "from ray.tune.examples.mnist_pytorch import get_data_loaders, ConvNet, train, test\n",
    "import optuna"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "<function ray.tune.examples.mnist_pytorch.get_data_loaders()>"
      ]
     },
     "execution_count": 3,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "get_data_loaders"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_mnist(trial):\n",
    "    use_cuda = torch.cuda.is_available()\n",
    "    device = torch.device(\"cuda\" if use_cuda else \"cpu\")\n",
    "    train_loader, test_loader = get_data_loaders()\n",
    "    print(train_loader, test_loader)\n",
    "    model = ConvNet().to(device)\n",
    "\n",
    "    optimizer = optim.SGD(\n",
    "       model.parameters(),\n",
    "       lr=trial.suggest_loguniform(\"lr\", 1e-4, 1e-2),\n",
    "       momentum=trial.suggest_uniform(\"momentum\", 0.1, 0.9))\n",
    "\n",
    "    for i in range(20):\n",
    "        train(model, optimizer, train_loader, device)\n",
    "        acc = test(model, test_loader, device)\n",
    "        trial.report(-acc, i)\n",
    "    return -acc"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:51:51,350]\u001b[0m A new study created in memory with name: no-name-041f10e5-3ed9-4fe8-a194-3deac39c8034\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB3E138400> <torch.utils.data.dataloader.DataLoader object at 0x000001BB3E155940>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:52:00,277]\u001b[0m Trial 0 finished with value: -0.709375 and parameters: {'lr': 0.002294876682481699, 'momentum': 0.2685036978384988}. Best is trial 0 with value: -0.709375.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB3E155C18> <torch.utils.data.dataloader.DataLoader object at 0x000001BB3E155A20>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:52:08,106]\u001b[0m Trial 1 finished with value: -0.465625 and parameters: {'lr': 0.002344175318635213, 'momentum': 0.2080562577223681}. Best is trial 0 with value: -0.709375.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB417D2518> <torch.utils.data.dataloader.DataLoader object at 0x000001BB417D25C0>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:52:15,820]\u001b[0m Trial 2 finished with value: -0.103125 and parameters: {'lr': 0.0002136044742818606, 'momentum': 0.4717006636618488}. Best is trial 0 with value: -0.709375.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB417D2860> <torch.utils.data.dataloader.DataLoader object at 0x000001BB417D2898>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:52:23,549]\u001b[0m Trial 3 finished with value: -0.146875 and parameters: {'lr': 0.0001260149480428593, 'momentum': 0.25094043136534216}. Best is trial 0 with value: -0.709375.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB417D2BA8> <torch.utils.data.dataloader.DataLoader object at 0x000001BB417D2BE0>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:52:31,460]\u001b[0m Trial 4 finished with value: -0.828125 and parameters: {'lr': 0.004268270264110353, 'momentum': 0.27595486649078077}. Best is trial 4 with value: -0.828125.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB417D2EF0> <torch.utils.data.dataloader.DataLoader object at 0x000001BB417D2F98>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:52:39,251]\u001b[0m Trial 5 finished with value: -0.828125 and parameters: {'lr': 0.0018987690869440878, 'momentum': 0.7071908464243633}. Best is trial 4 with value: -0.828125.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB3E176278> <torch.utils.data.dataloader.DataLoader object at 0x000001BB3E1762B0>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:52:47,872]\u001b[0m Trial 6 finished with value: -0.184375 and parameters: {'lr': 0.0002134785449996201, 'momentum': 0.2936567901481817}. Best is trial 4 with value: -0.828125.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB3E1765C0> <torch.utils.data.dataloader.DataLoader object at 0x000001BB3E1765F8>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:52:56,235]\u001b[0m Trial 7 finished with value: -0.378125 and parameters: {'lr': 0.00019274151360839007, 'momentum': 0.7687159781216226}. Best is trial 4 with value: -0.828125.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB3E176908> <torch.utils.data.dataloader.DataLoader object at 0x000001BB3E176940>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:53:04,597]\u001b[0m Trial 8 finished with value: -0.875 and parameters: {'lr': 0.0041249417845283754, 'momentum': 0.6337815233330691}. Best is trial 8 with value: -0.875.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<torch.utils.data.dataloader.DataLoader object at 0x000001BB3E176C50> <torch.utils.data.dataloader.DataLoader object at 0x000001BB3E176C88>\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[32m[I 2021-03-04 09:53:12,954]\u001b[0m Trial 9 finished with value: -0.309375 and parameters: {'lr': 0.0011924877221832489, 'momentum': 0.3926131701798178}. Best is trial 8 with value: -0.875.\u001b[0m\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Time taken: 81.61 seconds.\n",
      "Best config: {'lr': 0.0041249417845283754, 'momentum': 0.6337815233330691}\n"
     ]
    }
   ],
   "source": [
    "import time\n",
    "start = time.time()\n",
    "study = optuna.create_study()\n",
    "study.optimize(train_mnist, n_jobs=1, n_trials=10)\n",
    "taken = time.time() - start\n",
    "print(f\"Time taken: {taken:.2f} seconds.\")\n",
    "print(f\"Best config: {study.best_params}\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [],
   "source": [
    "import torch\n",
    "import torch.optim as optim\n",
    "from ray.tune.examples.mnist_pytorch import get_data_loaders, ConvNet, train, test\n",
    "from ray import tune\n",
    "from ray.tune.suggest.optuna import OptunaSearch\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def train_mnist(config):\n",
    "    use_cuda = torch.cuda.is_available()\n",
    "    device = torch.device(\"cuda\" if use_cuda else \"cpu\")\n",
    "    train_loader, test_loader = get_data_loaders()\n",
    "    model = ConvNet().to(device)\n",
    "    optimizer = optim.SGD(\n",
    "       model.parameters(), lr=config[\"lr\"], momentum=config[\"momentum\"])\n",
    "    for i in range(20):\n",
    "        train(model, optimizer, train_loader, device)\n",
    "        acc = test(model, test_loader, device)\n",
    "        tune.report(mean_accuracy=acc)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-03-04 10:52:16,092\tINFO services.py:1174 -- View the Ray dashboard at \u001b[1m\u001b[32mhttp://127.0.0.1:8265\u001b[39m\u001b[22m\n",
      "2021-03-04 10:52:25,379\tWARNING function_runner.py:541 -- Function checkpointing is disabled. This may result in unexpected behavior when using checkpointing features or certain schedulers. To enable, set the train function arguments to be `func(config, checkpoint_dir=None)`.\n",
      "\u001b[32m[I 2021-03-04 10:52:25,417]\u001b[0m A new study created in memory with name: optuna\u001b[0m\n",
      "2021-03-04 10:52:28,371\tERROR syncer.py:72 -- Log sync requires rsync to be installed.\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 11.4/15.9 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 1/8 CPUs, 0/0 GPUs, 0.0/2.98 GiB heap, 0.0/1.03 GiB objects<br>Result logdir: C:\\Users\\M1055951\\ray_results\\train_mnist_2021-03-04_10-52-25<br>Number of trials: 1/5 (1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name          </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">         lr</th><th style=\"text-align: right;\">  momentum</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>train_mnist_9c8ed192</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">0.000707492</td><td style=\"text-align: right;\">  0.239582</td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-03-04 10:52:30,809\tWARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 69a6825d641b461327313d1c01000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\n",
      "2021-03-04 10:52:30,817\tWARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 4ee449587774c1f0770a083801000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\n",
      "2021-03-04 10:52:30,818\tWARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID a67dc375e60ddd1a23bd3bb901000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\n",
      "2021-03-04 10:52:30,820\tWARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 480a853c2c4c6f276de42d0101000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\n",
      "2021-03-04 10:52:30,842\tERROR trial_runner.py:616 -- Trial train_mnist_9c8ed192: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 586, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 609, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1456, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=33932, ip=192.168.43.112)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 439, in ray._raylet.execute_task\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 176, in reraise_actor_init_error\n",
      "    raise self.actor_init_error\n",
      "  File \"python\\ray\\_raylet.pyx\", line 442, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 459, in ray._raylet.execute_task\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 282, in deserialize_objects\n",
      "    return context.deserialize_objects(data_metadata_pairs, object_refs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 245, in deserialize_objects\n",
      "    self._deserialize_object(data, metadata, object_ref))\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 192, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 170, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 160, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-03-04 10:52:30,858\tWARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 1e9d04d3b7e4dfb2e14dadbf01000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m 2021-03-04 10:52:30,818\tERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     from ray.tune.tune import run_experiments, run\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     from ray.tune.durable_trainable import DurableTrainable\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     from ray.tune.syncer import get_cloud_sync_client\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     @dataclass\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     return wrap(_cls)\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     if (_is_classvar(a_type, typing)\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m     return type(a_type) is typing._ClassVar\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m 2021-03-04 10:52:30,781\tERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     from ray.tune.tune import run_experiments, run\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     from ray.tune.durable_trainable import DurableTrainable\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     from ray.tune.syncer import get_cloud_sync_client\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     @dataclass\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     return wrap(_cls)\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     if (_is_classvar(a_type, typing)\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m     return type(a_type) is typing._ClassVar\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m 2021-03-04 10:52:30,779\tERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     from ray.tune.tune import run_experiments, run\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     from ray.tune.durable_trainable import DurableTrainable\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     from ray.tune.syncer import get_cloud_sync_client\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     @dataclass\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     return wrap(_cls)\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     if (_is_classvar(a_type, typing)\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m     return type(a_type) is typing._ClassVar\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m 2021-03-04 10:52:30,780\tERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     from ray.tune.tune import run_experiments, run\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     from ray.tune.durable_trainable import DurableTrainable\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     from ray.tune.syncer import get_cloud_sync_client\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     @dataclass\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     return wrap(_cls)\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     if (_is_classvar(a_type, typing)\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m     return type(a_type) is typing._ClassVar\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m 2021-03-04 10:52:30,780\tERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     from ray.tune.tune import run_experiments, run\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     from ray.tune.durable_trainable import DurableTrainable\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     from ray.tune.syncer import get_cloud_sync_client\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     @dataclass\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     return wrap(_cls)\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     if (_is_classvar(a_type, typing)\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m     return type(a_type) is typing._ClassVar\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m AttributeError: module 'typing' has no attribute '_ClassVar'\n"
     ]
    },
    {
     "ename": "AttributeError",
     "evalue": "'NoneType' object has no attribute 'get'",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mRayTaskError(AttributeError)\u001b[0m              Traceback (most recent call last)",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\u001b[0m in \u001b[0;36m_process_trial\u001b[1;34m(self, trial)\u001b[0m\n\u001b[0;32m    585\u001b[0m         \u001b[1;32mtry\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 586\u001b[1;33m             \u001b[0mresults\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrial_executor\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mfetch_result\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtrial\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    587\u001b[0m             with warn_if_slow(\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\u001b[0m in \u001b[0;36mfetch_result\u001b[1;34m(self, trial)\u001b[0m\n\u001b[0;32m    608\u001b[0m         \u001b[1;32mwith\u001b[0m \u001b[0mwarn_if_slow\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"fetch_result\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 609\u001b[1;33m             \u001b[0mresult\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mray\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtrial_future\u001b[0m\u001b[1;33m[\u001b[0m\u001b[1;36m0\u001b[0m\u001b[1;33m]\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtimeout\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mDEFAULT_GET_TIMEOUT\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    610\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\u001b[0m in \u001b[0;36mwrapper\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     46\u001b[0m             \u001b[1;32mreturn\u001b[0m \u001b[0mgetattr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mray\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mfunc\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m__name__\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 47\u001b[1;33m         \u001b[1;32mreturn\u001b[0m \u001b[0mfunc\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m*\u001b[0m\u001b[0margs\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;33m**\u001b[0m\u001b[0mkwargs\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m     48\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\u001b[0m in \u001b[0;36mget\u001b[1;34m(object_refs, timeout)\u001b[0m\n\u001b[0;32m   1455\u001b[0m                 \u001b[1;32mif\u001b[0m \u001b[0misinstance\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mvalue\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mRayTaskError\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m-> 1456\u001b[1;33m                     \u001b[1;32mraise\u001b[0m \u001b[0mvalue\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mas_instanceof_cause\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m   1457\u001b[0m                 \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mRayTaskError(AttributeError)\u001b[0m: \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=33932, ip=192.168.43.112)\n  File \"python\\ray\\_raylet.pyx\", line 439, in ray._raylet.execute_task\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 176, in reraise_actor_init_error\n    raise self.actor_init_error\n  File \"python\\ray\\_raylet.pyx\", line 442, in ray._raylet.execute_task\n  File \"python\\ray\\_raylet.pyx\", line 459, in ray._raylet.execute_task\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 282, in deserialize_objects\n    return context.deserialize_objects(data_metadata_pairs, object_refs)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 245, in deserialize_objects\n    self._deserialize_object(data, metadata, object_ref))\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 192, in _deserialize_object\n    return self._deserialize_msgpack_data(data, metadata_fields)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 170, in _deserialize_msgpack_data\n    python_objects = self._deserialize_pickle5_data(pickle5_data)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 160, in _deserialize_pickle5_data\n    obj = pickle.loads(in_band)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n    from ray.tune.tune import run_experiments, run\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n    from ray.tune.ray_trial_executor import RayTrialExecutor\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n    from ray.tune.durable_trainable import DurableTrainable\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n    from ray.tune.syncer import get_cloud_sync_client\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n    @dataclass\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n    return wrap(_cls)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n    for name, type in cls_annotations.items()]\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n    for name, type in cls_annotations.items()]\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n    if (_is_classvar(a_type, typing)\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n    return type(a_type) is typing._ClassVar\nAttributeError: module 'typing' has no attribute '_ClassVar'",
      "\nDuring handling of the above exception, another exception occurred:\n",
      "\u001b[1;31mAttributeError\u001b[0m                            Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-3-5e38d8b0b15e>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     10\u001b[0m    \u001b[0mmode\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"max\"\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     11\u001b[0m    \u001b[0msearch_alg\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mOptunaSearch\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 12\u001b[1;33m    num_samples=5)\n\u001b[0m\u001b[0;32m     13\u001b[0m \u001b[0mtaken\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m-\u001b[0m \u001b[0mstart\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     14\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34mf\"Time taken: {taken:.2f} seconds.\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, loggers, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint)\u001b[0m\n\u001b[0;32m    419\u001b[0m     \u001b[0mtune_start\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mtime\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtime\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    420\u001b[0m     \u001b[1;32mwhile\u001b[0m \u001b[1;32mnot\u001b[0m \u001b[0mrunner\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mis_finished\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 421\u001b[1;33m         \u001b[0mrunner\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mstep\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    422\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mhas_verbosity\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mVerbosity\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mV1_EXPERIMENT\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    423\u001b[0m             \u001b[0m_report_progress\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mrunner\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mprogress_reporter\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\u001b[0m in \u001b[0;36mstep\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    400\u001b[0m                 \u001b[1;32mif\u001b[0m \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrial_executor\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0min_staging_grace_period\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    401\u001b[0m                     \u001b[0mtimeout\u001b[0m \u001b[1;33m=\u001b[0m \u001b[1;36m0.1\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 402\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_process_events\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mtimeout\u001b[0m\u001b[1;33m)\u001b[0m  \u001b[1;31m# blocking\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    403\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    404\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrial_executor\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mon_no_available_trials\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\u001b[0m in \u001b[0;36m_process_events\u001b[1;34m(self, timeout)\u001b[0m\n\u001b[0;32m    558\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    559\u001b[0m                 \u001b[1;32mwith\u001b[0m \u001b[0mwarn_if_slow\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"process_trial\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 560\u001b[1;33m                     \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_process_trial\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtrial\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    561\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    562\u001b[0m             \u001b[1;31m# `self._queued_trial_decisions` now contains a final decision\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\u001b[0m in \u001b[0;36m_process_trial\u001b[1;34m(self, trial)\u001b[0m\n\u001b[0;32m    615\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    616\u001b[0m                 \u001b[0mlogger\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mexception\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0merror_msg\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 617\u001b[1;33m             \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_process_trial_failure\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtrial\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtraceback\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mformat_exc\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    618\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    619\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0m_process_trial_result\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtrial\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mresult\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\u001b[0m in \u001b[0;36m_process_trial_failure\u001b[1;34m(self, trial, error_msg)\u001b[0m\n\u001b[0;32m    824\u001b[0m             \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    825\u001b[0m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_scheduler_alg\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mon_trial_error\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mtrial\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 826\u001b[1;33m                 \u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_search_alg\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mon_trial_complete\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mtrial\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mtrial_id\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0merror\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;32mTrue\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    827\u001b[0m                 self._callbacks.on_trial_error(\n\u001b[0;32m    828\u001b[0m                     \u001b[0miteration\u001b[0m\u001b[1;33m=\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_iteration\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\suggest\\search_generator.py\u001b[0m in \u001b[0;36mon_trial_complete\u001b[1;34m(self, trial_id, result, error)\u001b[0m\n\u001b[0;32m    128\u001b[0m                           error: bool = False):\n\u001b[0;32m    129\u001b[0m         self.searcher.on_trial_complete(\n\u001b[1;32m--> 130\u001b[1;33m             trial_id=trial_id, result=result, error=error)\n\u001b[0m\u001b[0;32m    131\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    132\u001b[0m     \u001b[1;32mdef\u001b[0m \u001b[0mis_finished\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m)\u001b[0m \u001b[1;33m->\u001b[0m \u001b[0mbool\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\suggest\\optuna.py\u001b[0m in \u001b[0;36mon_trial_complete\u001b[1;34m(self, trial_id, result, error)\u001b[0m\n\u001b[0;32m    220\u001b[0m         \u001b[0mot_trial_id\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mot_trial\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_trial_id\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    221\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 222\u001b[1;33m         \u001b[0mval\u001b[0m \u001b[1;33m=\u001b[0m \u001b[0mresult\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mmetric\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;32mNone\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    223\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mhasattr\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mself\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0m_storage\u001b[0m\u001b[1;33m,\u001b[0m \u001b[1;34m\"set_trial_value\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    224\u001b[0m             \u001b[1;31m# Backwards compatibility with optuna < 2.4.0\u001b[0m\u001b[1;33m\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mAttributeError\u001b[0m: 'NoneType' object has no attribute 'get'"
     ]
    }
   ],
   "source": [
    "import time\n",
    "start = time.time()\n",
    "analysis = tune.run(\n",
    "   train_mnist,\n",
    "   config={\n",
    "       \"lr\": tune.loguniform(1e-4, 1e-2),\n",
    "       \"momentum\": tune.uniform(0.1, 0.9),\n",
    "   },\n",
    "   metric=\"mean_accuracy\",\n",
    "   mode=\"max\",\n",
    "   search_alg=OptunaSearch(),\n",
    "   num_samples=5)\n",
    "taken = time.time() - start\n",
    "print(f\"Time taken: {taken:.2f} seconds.\")\n",
    "print(f\"Best config: {analysis.best_config}\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 11.3/15.9 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 1/8 CPUs, 0/0 GPUs, 0.0/2.98 GiB heap, 0.0/1.03 GiB objects<br>Result logdir: C:\\Users\\M1055951\\ray_results\\train_mnist_2021-03-04_10-56-02<br>Number of trials: 1/3 (1 RUNNING)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name             </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">   lr</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>train_mnist_1c2f7_00000</td><td>RUNNING </td><td>     </td><td style=\"text-align: right;\">0.001</td></tr>\n",
       "</tbody>\n",
       "</table><br><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-03-04 10:56:04,356\tWARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID c6953afc4a9f69e91488ca7c01000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\n",
      "2021-03-04 10:56:04,391\tERROR trial_runner.py:616 -- Trial train_mnist_1c2f7_00000: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 586, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 609, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1456, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=16500, ip=192.168.43.112)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 439, in ray._raylet.execute_task\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 176, in reraise_actor_init_error\n",
      "    raise self.actor_init_error\n",
      "  File \"python\\ray\\_raylet.pyx\", line 442, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 459, in ray._raylet.execute_task\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 282, in deserialize_objects\n",
      "    return context.deserialize_objects(data_metadata_pairs, object_refs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 245, in deserialize_objects\n",
      "    self._deserialize_object(data, metadata, object_ref))\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 192, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 170, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 160, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m 2021-03-04 10:56:04,337\tERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     from ray.tune.tune import run_experiments, run\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     from ray.tune.durable_trainable import DurableTrainable\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     from ray.tune.syncer import get_cloud_sync_client\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     @dataclass\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     return wrap(_cls)\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     if (_is_classvar(a_type, typing)\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m     return type(a_type) is typing._ClassVar\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "2021-03-04 10:56:04,459\tWARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID 753565f917242c119e81ccf701000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=16500)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m 2021-03-04 10:56:04,427\tERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     from ray.tune.tune import run_experiments, run\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     from ray.tune.durable_trainable import DurableTrainable\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     from ray.tune.syncer import get_cloud_sync_client\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     @dataclass\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     return wrap(_cls)\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     if (_is_classvar(a_type, typing)\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m     return type(a_type) is typing._ClassVar\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "2021-03-04 10:56:04,490\tERROR trial_runner.py:616 -- Trial train_mnist_1c2f7_00001: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 586, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 609, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1456, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=15828, ip=192.168.43.112)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 439, in ray._raylet.execute_task\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 176, in reraise_actor_init_error\n",
      "    raise self.actor_init_error\n",
      "  File \"python\\ray\\_raylet.pyx\", line 442, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 459, in ray._raylet.execute_task\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 282, in deserialize_objects\n",
      "    return context.deserialize_objects(data_metadata_pairs, object_refs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 245, in deserialize_objects\n",
      "    self._deserialize_object(data, metadata, object_ref))\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 192, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 170, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 160, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "2021-03-04 10:56:04,505\tWARNING worker.py:1107 -- Failed to unpickle actor class 'ImplicitFunc' for actor ID e320f439b49c51573c28d4a901000000. Traceback:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "    actor_class = pickle.loads(pickled_class)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2021-03-04 10:56:04,534\tERROR trial_runner.py:616 -- Trial train_mnist_1c2f7_00002: Error processing event.\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\trial_runner.py\", line 586, in _process_trial\n",
      "    results = self.trial_executor.fetch_result(trial)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 609, in fetch_result\n",
      "    result = ray.get(trial_future[0], timeout=DEFAULT_GET_TIMEOUT)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\_private\\client_mode_hook.py\", line 47, in wrapper\n",
      "    return func(*args, **kwargs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 1456, in get\n",
      "    raise value.as_instanceof_cause()\n",
      "ray.exceptions.RayTaskError(AttributeError): \u001b[36mray::ImplicitFunc.train_buffered()\u001b[39m (pid=24308, ip=192.168.43.112)\n",
      "  File \"python\\ray\\_raylet.pyx\", line 439, in ray._raylet.execute_task\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 176, in reraise_actor_init_error\n",
      "    raise self.actor_init_error\n",
      "  File \"python\\ray\\_raylet.pyx\", line 442, in ray._raylet.execute_task\n",
      "  File \"python\\ray\\_raylet.pyx\", line 459, in ray._raylet.execute_task\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\worker.py\", line 282, in deserialize_objects\n",
      "    return context.deserialize_objects(data_metadata_pairs, object_refs)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 245, in deserialize_objects\n",
      "    self._deserialize_object(data, metadata, object_ref))\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 192, in _deserialize_object\n",
      "    return self._deserialize_msgpack_data(data, metadata_fields)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 170, in _deserialize_msgpack_data\n",
      "    python_objects = self._deserialize_pickle5_data(pickle5_data)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\serialization.py\", line 160, in _deserialize_pickle5_data\n",
      "    obj = pickle.loads(in_band)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "    from ray.tune.tune import run_experiments, run\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "    from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "    from ray.tune.durable_trainable import DurableTrainable\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "    from ray.tune.syncer import get_cloud_sync_client\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "    @dataclass\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "    return wrap(_cls)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "    return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "    for name, type in cls_annotations.items()]\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "    if (_is_classvar(a_type, typing)\n",
      "  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "    return type(a_type) is typing._ClassVar\n",
      "AttributeError: module 'typing' has no attribute '_ClassVar'\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Result for train_mnist_1c2f7_00000:\n",
      "  {}\n",
      "  \n",
      "Result for train_mnist_1c2f7_00001:\n",
      "  {}\n",
      "  \n",
      "Result for train_mnist_1c2f7_00002:\n",
      "  {}\n",
      "  \n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=15828)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m 2021-03-04 10:56:04,479\tERROR function_manager.py:498 -- Failed to load actor class ImplicitFunc.\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m Traceback (most recent call last):\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\function_manager.py\", line 496, in _load_actor_class_from_gcs\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     actor_class = pickle.loads(pickled_class)\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\__init__.py\", line 2, in <module>\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     from ray.tune.tune import run_experiments, run\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\", line 13, in <module>\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     from ray.tune.ray_trial_executor import RayTrialExecutor\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\ray_trial_executor.py\", line 17, in <module>\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     from ray.tune.durable_trainable import DurableTrainable\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\durable_trainable.py\", line 5, in <module>\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     from ray.tune.syncer import get_cloud_sync_client\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\syncer.py\", line 89, in <module>\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     @dataclass\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 958, in dataclass\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     return wrap(_cls)\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 950, in wrap\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     return _process_class(cls, init, repr, eq, order, unsafe_hash, frozen)\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in _process_class\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 801, in <listcomp>\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     for name, type in cls_annotations.items()]\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 659, in _get_field\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     if (_is_classvar(a_type, typing)\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m   File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\dataclasses.py\", line 550, in _is_classvar\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m     return type(a_type) is typing._ClassVar\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m AttributeError: module 'typing' has no attribute '_ClassVar'\n",
      "2021-03-04 10:56:04,590\tWARNING tune.py:429 -- Trial Runner checkpointing failed: [WinError 183] Cannot create a file when that file already exists: 'C:\\\\Users\\\\M1055951\\\\ray_results\\\\train_mnist_2021-03-04_10-56-02\\\\.tmp_generator' -> 'C:\\\\Users\\\\M1055951\\\\ray_results\\\\train_mnist_2021-03-04_10-56-02\\\\basic-variant-state-2021-03-04_10-56-02.json'\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "== Status ==<br>Memory usage on this node: 11.3/15.9 GiB<br>Using FIFO scheduling algorithm.<br>Resources requested: 0/8 CPUs, 0/0 GPUs, 0.0/2.98 GiB heap, 0.0/1.03 GiB objects<br>Result logdir: C:\\Users\\M1055951\\ray_results\\train_mnist_2021-03-04_10-56-02<br>Number of trials: 3/3 (3 ERROR)<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name             </th><th>status  </th><th>loc  </th><th style=\"text-align: right;\">   lr</th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>train_mnist_1c2f7_00000</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">0.001</td></tr>\n",
       "<tr><td>train_mnist_1c2f7_00001</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">0.01 </td></tr>\n",
       "<tr><td>train_mnist_1c2f7_00002</td><td>ERROR   </td><td>     </td><td style=\"text-align: right;\">0.1  </td></tr>\n",
       "</tbody>\n",
       "</table><br>Number of errored trials: 3<br><table>\n",
       "<thead>\n",
       "<tr><th>Trial name             </th><th style=\"text-align: right;\">  # failures</th><th>error file                                                                                                                    </th></tr>\n",
       "</thead>\n",
       "<tbody>\n",
       "<tr><td>train_mnist_1c2f7_00000</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\M1055951\\ray_results\\train_mnist_2021-03-04_10-56-02\\train_mnist_1c2f7_00000_0_lr=0.001_2021-03-04_10-56-02\\error.txt</td></tr>\n",
       "<tr><td>train_mnist_1c2f7_00001</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\M1055951\\ray_results\\train_mnist_2021-03-04_10-56-02\\train_mnist_1c2f7_00001_1_lr=0.01_2021-03-04_10-56-02\\error.txt </td></tr>\n",
       "<tr><td>train_mnist_1c2f7_00002</td><td style=\"text-align: right;\">           1</td><td>C:\\Users\\M1055951\\ray_results\\train_mnist_2021-03-04_10-56-02\\train_mnist_1c2f7_00002_2_lr=0.1_2021-03-04_10-56-02\\error.txt  </td></tr>\n",
       "</tbody>\n",
       "</table><br>"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "ename": "TuneError",
     "evalue": "('Trials did not complete', [train_mnist_1c2f7_00000, train_mnist_1c2f7_00001, train_mnist_1c2f7_00002])",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mTuneError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[1;32m<ipython-input-4-0eae6f16d548>\u001b[0m in \u001b[0;36m<module>\u001b[1;34m()\u001b[0m\n\u001b[0;32m     16\u001b[0m analysis = tune.run(\n\u001b[0;32m     17\u001b[0m     \u001b[0mtrain_mnist\u001b[0m\u001b[1;33m,\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m---> 18\u001b[1;33m     config={\"lr\": tune.grid_search([0.001, 0.01, 0.1])})\n\u001b[0m\u001b[0;32m     19\u001b[0m \u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m     20\u001b[0m \u001b[0mprint\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Best config: \"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0manalysis\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0mget_best_config\u001b[0m\u001b[1;33m(\u001b[0m\u001b[0mmetric\u001b[0m\u001b[1;33m=\u001b[0m\u001b[1;34m\"mean_accuracy\"\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;32mC:\\ProgramData\\Anaconda3\\lib\\site-packages\\ray\\tune\\tune.py\u001b[0m in \u001b[0;36mrun\u001b[1;34m(run_or_experiment, name, metric, mode, stop, time_budget_s, config, resources_per_trial, num_samples, local_dir, search_alg, scheduler, keep_checkpoints_num, checkpoint_score_attr, checkpoint_freq, checkpoint_at_end, verbose, progress_reporter, log_to_file, trial_name_creator, trial_dirname_creator, sync_config, export_formats, max_failures, fail_fast, restore, server_port, resume, queue_trials, reuse_actors, trial_executor, raise_on_failed_trial, callbacks, loggers, ray_auto_init, run_errored_only, global_checkpoint_period, with_server, upload_dir, sync_to_cloud, sync_to_driver, sync_on_checkpoint)\u001b[0m\n\u001b[0;32m    442\u001b[0m     \u001b[1;32mif\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    443\u001b[0m         \u001b[1;32mif\u001b[0m \u001b[0mraise_on_failed_trial\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[1;32m--> 444\u001b[1;33m             \u001b[1;32mraise\u001b[0m \u001b[0mTuneError\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Trials did not complete\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0m\u001b[0;32m    445\u001b[0m         \u001b[1;32melse\u001b[0m\u001b[1;33m:\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n\u001b[0;32m    446\u001b[0m             \u001b[0mlogger\u001b[0m\u001b[1;33m.\u001b[0m\u001b[0merror\u001b[0m\u001b[1;33m(\u001b[0m\u001b[1;34m\"Trials did not complete: %s\"\u001b[0m\u001b[1;33m,\u001b[0m \u001b[0mincomplete_trials\u001b[0m\u001b[1;33m)\u001b[0m\u001b[1;33m\u001b[0m\u001b[0m\n",
      "\u001b[1;31mTuneError\u001b[0m: ('Trials did not complete', [train_mnist_1c2f7_00000, train_mnist_1c2f7_00001, train_mnist_1c2f7_00002])"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=24308)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=32640)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=22172)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=14788)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=8924)\u001b[0m \n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m Windows fatal exception: access violation\n",
      "\u001b[2m\u001b[36m(pid=33932)\u001b[0m \n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import torch.optim as optim\n",
    "from ray import tune\n",
    "from ray.tune.examples.mnist_pytorch import get_data_loaders, ConvNet, train, test\n",
    "\n",
    "\n",
    "def train_mnist(config):\n",
    "    train_loader, test_loader = get_data_loaders()\n",
    "    model = ConvNet(config)\n",
    "    optimizer = optim.SGD(model.parameters(), lr=config[\"lr\"])\n",
    "    for i in range(30):\n",
    "        train(model, optimizer, train_loader, torch.device(\"cpu\"))\n",
    "        acc = test(model, test_loader, torch.device(\"cpu\"))\n",
    "        tune.track.log(mean_accuracy=acc)\n",
    "\n",
    "analysis = tune.run(\n",
    "    train_mnist,\n",
    "    config={\"lr\": tune.grid_search([0.001, 0.01, 0.1])})\n",
    "\n",
    "print(\"Best config: \", analysis.get_best_config(metric=\"mean_accuracy\"))\n",
    "\n",
    "# Get a dataframe for analyzing trial results.\n",
    "df = analysis.dataframe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
